// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Lhr6DDjQOy-LxMbVY_0oc4T0RBWb2po',
    appId: '1:127014310872:web:0dad8b7f72ffefa490d8ad',
    messagingSenderId: '127014310872',
    projectId: 'jononipharmacy-1124c',
    authDomain: 'jononipharmacy-1124c.firebaseapp.com',
    storageBucket: 'jononipharmacy-1124c.firebasestorage.app',
    measurementId: 'G-L0GKSEEM3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdl5rI1ExY_aitNyLKYNqJzxWGFu1pMvY',
    appId: '1:127014310872:android:73910ab9f9f2479390d8ad',
    messagingSenderId: '127014310872',
    projectId: 'jononipharmacy-1124c',
    storageBucket: 'jononipharmacy-1124c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ41u4gYW0DezZRNC6Jmtadg73Ml3ulTI',
    appId: '1:127014310872:ios:8e8e733c2eddb53590d8ad',
    messagingSenderId: '127014310872',
    projectId: 'jononipharmacy-1124c',
    storageBucket: 'jononipharmacy-1124c.firebasestorage.app',
    iosBundleId: 'com.example.jononipharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ41u4gYW0DezZRNC6Jmtadg73Ml3ulTI',
    appId: '1:127014310872:ios:8e8e733c2eddb53590d8ad',
    messagingSenderId: '127014310872',
    projectId: 'jononipharmacy-1124c',
    storageBucket: 'jononipharmacy-1124c.firebasestorage.app',
    iosBundleId: 'com.example.jononipharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Lhr6DDjQOy-LxMbVY_0oc4T0RBWb2po',
    appId: '1:127014310872:web:0e9720630c16fc8c90d8ad',
    messagingSenderId: '127014310872',
    projectId: 'jononipharmacy-1124c',
    authDomain: 'jononipharmacy-1124c.firebaseapp.com',
    storageBucket: 'jononipharmacy-1124c.firebasestorage.app',
    measurementId: 'G-P1B32S7GPD',
  );
}
